services:
  shortener_db:
    container_name: shortener_db
    build:
      context: ./db/
      dockerfile: Dockerfile
    command: >
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
      -c max_connections=1000
      -c work_mem=2048MB
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: shortener-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpw_42
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U postgres -d shortener-db
      interval: 10s
      timeout: 3s
      retries: 3